"""
SentinelAI AI Engine - MongoDB Connection Utility
==================================================

This module handles the connection to MongoDB and provides utility functions
to fetch logs for AI preprocessing and anomaly detection.

The logs are generated by the Node.js demo application using Winston logger
and stored in MongoDB with the following schema:
    - timestamp: Date when the log was created
    - level: Log level (info, warn, error)
    - message: Log message content
    - service: Service name that generated the log
    - metadata: Additional contextual information
    - createdAt: MongoDB document creation time
"""

import os
from datetime import datetime, timedelta
from typing import List, Dict, Optional
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError


# MongoDB client instance (singleton pattern for connection reuse)
_client: Optional[MongoClient] = None


def get_client() -> Optional[MongoClient]:
    """
    Get or create a MongoDB client connection.
    
    Uses a singleton pattern to reuse the connection across multiple calls.
    Reads the MongoDB URI from the MONGODB_URI environment variable.
    
    Returns:
        MongoClient instance or None if connection fails
    """
    global _client
    
    if _client is not None:
        return _client
    
    mongodb_uri = os.getenv("MONGODB_URI")
    
    if not mongodb_uri:
        print("[ERROR] MONGODB_URI environment variable is not set")
        return None
    
    try:
        # Create client with a reasonable timeout for AI workloads
        _client = MongoClient(mongodb_uri, serverSelectionTimeoutMS=5000)
        
        # Verify connection by pinging the server
        _client.admin.command("ping")
        print("[INFO] Successfully connected to MongoDB")
        
        return _client
        
    except (ConnectionFailure, ServerSelectionTimeoutError) as e:
        print(f"[ERROR] Failed to connect to MongoDB: {e}")
        return None


def get_database():
    """
    Get the MongoDB database instance.
    
    Returns:
        Database instance or None if connection fails
    """
    client = get_client()
    
    if client is None:
        return None
    
    # Extract database name from URI or use default
    # The database name is typically the last part of the URI path
    mongodb_uri = os.getenv("MONGODB_URI", "")
    
    # Parse database name from URI (format: mongodb://host:port/database)
    if "/" in mongodb_uri:
        db_name = mongodb_uri.split("/")[-1].split("?")[0]
    else:
        db_name = "sentinelai_logs"
    
    return client[db_name]


def fetch_logs(minutes: int = 60) -> List[Dict]:
    """
    Fetch logs from MongoDB for the specified time window.
    
    This function retrieves logs from the last N minutes, sorted by timestamp
    in ascending order. This ordering is important for time-series analysis
    and sequential pattern detection in the AI model.
    
    Args:
        minutes: Number of minutes to look back (default: 60)
    
    Returns:
        List of log documents as dictionaries, sorted by timestamp ascending.
        Returns an empty list if connection fails or no logs are found.
    
    Example:
        >>> logs = fetch_logs(minutes=30)
        >>> print(f"Fetched {len(logs)} logs from the last 30 minutes")
    """
    db = get_database()
    
    if db is None:
        print("[WARN] Cannot fetch logs - database connection unavailable")
        return []
    
    try:
        # Calculate the time threshold for the query
        time_threshold = datetime.utcnow() - timedelta(minutes=minutes)
        
        # Query logs collection with time filter
        # Sorting by timestamp ascending ensures chronological order for AI processing
        logs_collection = db["logs"]
        
        cursor = logs_collection.find(
            {"timestamp": {"$gte": time_threshold}}
        ).sort("timestamp", 1)  # 1 = ascending order
        
        # Convert cursor to list of dictionaries
        logs = list(cursor)
        
        print(f"[INFO] Fetched {len(logs)} logs from the last {minutes} minutes")
        
        return logs
        
    except Exception as e:
        print(f"[ERROR] Failed to fetch logs: {e}")
        return []


def close_connection():
    """
    Close the MongoDB connection.
    
    Should be called when the application shuts down to release resources.
    """
    global _client
    
    if _client is not None:
        _client.close()
        _client = None
        print("[INFO] MongoDB connection closed")
